<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <AssemblyVersion>1.0.0.0</AssemblyVersion>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageProjectUrl>https://github.com/linkmadao/teste-gerenciador-tarefas</PackageProjectUrl>
    </PropertyGroup>

    <ItemGroup>
      <None Include="..\..\README.md">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GerenciadorTarefas.Infra.Ioc\GerenciadorTarefas.Infra.Ioc.csproj" />
    </ItemGroup>
</Project>
